### ISSUE TITLE
Presentere innhold i sidebar basert på artikkeltype som vises?

### ISSUE THREAD

**Issue by sjoholt** [ghp91/Group-7---Main-project#7]

**Comment by DemyxIX** [comment]
<?php
$qget = "SELECT TOP 10 \* FROM artikkel order by artikkelID desc" ;
$fget = sqlsrv_query( $conn, $qget);
if ( $fget === false ) {
   echo "Error in statement preparation/execution.\n";
   die( print_r( sqlsrv_errors(), true));
}

while( $row = sqlsrv_fetch_array( $fget, SQLSRV_FETCH_ASSOC)){

$articleID = $row['artikkelID'];//sqlsrv_get_field( $stmt, 0 );
$tittel = $row['tittel'];//sqlsrv_get_field( $stmt, 1 );
$tekst = $row['tekst'];//sqlsrv_get_field( $stmt, 2 );
$ingress = $row['ingress'];//sqlsrv_get_field( $stmt, 3 );
$bildeURL = $row['bildeurl'];//sqlsrv_get_field( $stmt, 4 );

if ( $tittel === false ) {
   die( print_r( sqlsrv_errors(), true ));
}
echo '<h1>' . $tittel . '</h1>'; 
echo '<img src="'.$bildeURL.'">';
echo '<h4>' . $ingress . '</h4>';
echo '<p>' . $tekst . '</p>'; 
}
sqlsrv_close( $conn);
?>
